#!/usr/bin/env ansible-playbook

- name: Configure Platform
  hosts: localhost
  vars:
    use_root_for_install: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  roles:
    - role: python
      tags: [ python, programming ]
    - role: rust
      tags: [ rust, programming ]
    - role: golang
      tags: [ golang, programming ]
    - role: fish
      tags: [ fish, shell ]
    - role: node
      tags: [ nodejs, programming ]
    - role: starship
      tags: [ starship, shell ]
    - role: tmux
      tags: [ tmux, shell ]
    - role: nvim
      tags: [ nvim, tools ]