#!/usr/bin/env ansible-playbook

- name: Install Apps and Configs
  hosts: localhost
  vars:
    use_root_for_install: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
    go_version: "1.21.6"
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }
  environment:
    CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  tasks:
    - name: Install Rust
      import_tasks:
        file: rust/install.yml
      tags:
        - rust
        - fish
        - alacritty
        - starship

    - name: Install Fish
      import_tasks:
        file: fish/install.yml
      tags:
        - fish
        
    - name: Install Tmux
      import_tasks:
        file: tmux/install.yml
      tags:
        - tmux

    # - name: Install Alacritty
    #   import_tasks:
    #     file: alacritty/install.yml
    #   tags:
    #     - alacritty
    
    - name: Install Starship
      import_tasks:
        file: starship/install.yml
      tags:
        - starship

    - name: Install NVIM
      import_tasks:
        file: nvim/install.yml
      tags:
        - nvim