- name: Install Native Packages
  become: "{{ use_root_for_install }}"
  when: package_settings[ansible_facts['distribution'] | lower].packages | length > 0
  package:
    name: "{{ package_settings[ansible_facts['distribution'] | lower].packages }}"
    state: present

- name: Clean Existing Config
  file:
    path: "{{ansible_env.HOME}}/.config/nvim"
    state: absent

- name: Template Clean Config
  include_tasks: template_config_file.yml
  when: item.state != 'directory'
  vars:
    item: "{{item}}"
  with_community.general.filetree: ../templates/