name: Docker Image Publish

on:
  push:
    branches:
      - main

concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-publish:
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
            platform: [
                {"file": "ubuntu.Dockerfile", "tag": "ubuntu"}
            ]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.platform.file }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository_owner }}/dotfiles:${{ matrix.platform.tag }}